version: '3'
services:
  fashop:
    depends_on:
      - mysql
    links:
      - mysql
    image: ezkuangren/swoole1
    ports:
      - ${FASHOP_PORT}:9510
    volumes:
      - ./:/var/www/project
    stdin_open: true
    tty: true
    privileged: true
    command: ["php", "/var/www/project/volumes/bin/fashop.php"]

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    networks:
      - default

  fashop-admin:
    image: ezkuangren/fashop-admin:latest
    environment:
      FASHOP_ADMIN_VERSION: "${FASHOP_ADMIN_VERSION}"
    volumes:
      - ${SOURCE_DIR}:/fashop-admin-code
    tty: true
    privileged: true
    command: ["node", "/fashop-admin-code/volumes/bin/fashop-admin.js"]

